In [1]:
import pandas as pd

In [2]:
Breed_dev = pd.DataFrame(columns=["Breed_extra","Breed_Life","Breed_Size",
                                  "Breed_Acti","Breed_Smrt","Breed_Fmly","Breed_Agve"])
Breed_dev["Breed_extra"] = ['Abyssinian','Angora','Affenpinscher', 'AfghanHound', 'AiredaleTerrier',
       'Akita', 'AlaskanHusky', 'AlaskanMalamute',
       'AmericanBulldog', 'AmericanEskimo', 'AmericanFoxhound',
       'AmericanPitBullTerrier', 'AmericanStaffordshireTerrier',
       'AnatolShepherd', 'AustralianCattleDog',
       'AustralianKelpie', 'AustralianShepherd', 'AustralianTerrier',
       'Balinese', 'Basenji', 'BassetHound', 'Beagle', 'BeardedCollie',
       'Beauceron', 'BedlingtonTerr', 'BelgianMalinois', 'BelgianSheepdog',
       'BelgianTervuren', 'Bengal', 'BerneseMountainDog', 'BichonFrise',
       'BlackMouthCur', 'Bloodhound', 'BlueLacy', 'BluetickHound',
       'Boerboel', 'Bombay', 'BorderCollie', 'BorderTerrier', 'Borzoi',
       'BostonTerrier', 'Boxer', 'BoykinSpan', 'Brittany',         
       'BrussGriffon', 'BullTerrier', 'BullTerrierMiniature', 'Bulldog',
       'Bullmastiff', 'Burmese', 'CairnTerrier', 'CanaanDog', 'CaneCorso',
       'CardiganWelshCorgi', 'CarolinaDog', 'Catahoula', 'CavalierSpan',     
       'ChesaBayRetr', 'Chihuahua', 'ChineseCrested', 'ChineseSharpei',    
       'ChowChow', 'CockerSpaniel', 'CollieRough', 'CollieSmooth',
                            
       'CornishRex', 'Cymric', 'Dachshund', 'DachshundWirehair',
       'Dalmatian', 'DevonRex']
 
Breed_dev["Breed_Life"] = [12,11.5,13,15,12.5,11.5,12.5,12,12.5,14,12,11.5,14,12,14,11.5,13.5,13,20,13.5,12.5,12.5,13,11,13.5,15,13,13,11.5,\
                          8.5,14.5,15,11,16,11.5,10,17,13.5,13.5,11.5,12,11,12.5,13,13.5,12.5,12,9,8,13.5,14,13.5,10.5,13.5,13.5,12,\
                          13.5,11.5,15,15.5,10,10,12,13,13,11.5,12,14,14,12,12.5] #수명
Breed_dev["Breed_Size"] = [1,1,1,3,3,3,2,3,3,2,3,1,3,3,2,3,2,1,0,2,2,2,2,3,1,3,3,3,1,3,1,2,3,2,3,3,0,2,1,3,1,3,2,2,1,3,2,2,3,1,1,2,2,2,2,3,1,3,0,1,2,3,2,3,3,0,1,1,1,3,0] #크기(0,1,2,3단계-[4kg미만, 10kg미만, 25kg미만, 25kg이상])
Breed_dev["Breed_Acti"] = [0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,2,1,1,1,1,1,0,0,1,1,1,0,0,1,1,1,0] #활동성
Breed_dev["Breed_Smrt"] = [1,1,0,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,0,0,1,0,0,0,1,1,0,1,1,1,0,1,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1] #영리함
Breed_dev["Breed_Fmly"] = [0,0,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0] #사교성, 충성심
Breed_dev["Breed_Agve"] = [0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] #공격성 (pitbull류)
                           
Breed_dev.tail()



# 위 리스트에서 제외한 것 : 'American' , 'Black', , 'British'

,Breed_extra,Breed_Life,Breed_Size,Breed_Acti,Breed_Smrt,Breed_Fmly,Breed_Agve
66,Cymric,12.0,1,0,1,0,0
67,Dachshund,14.0,1,1,1,1,0
68,DachshundWirehair,14.0,1,1,1,1,0
69,Dalmatian,12.0,3,1,1,1,0
70,DevonRex,12.5,0,0,1,0,0